language: java
jdk:
  - openjdk11

env:
  global:
    - DOCKER_IMAGE_TAG=tobiassu87/docker-course:travis-tagged

services:
  - docker

script:
  - docker build -t $DOCKER_IMAGE_TAG .

deploy:
  - provider: script
    script: bash docker_push.sh
    on:
      branch: main

  - provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-course"
    env: "DockerCourse-env-docker-compose"
    bucket_name: "elasticbeanstalk-eu-central-1-793601222992"
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
