language: java
jdk:
  - openjdk11

env:
  - DOCKER_IMAGE_TAG=tobiassu87/docker-course:travis-tagged

services:
  - docker

script:
  - docker build -t $DOCKER_IMAGE_TAG .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: main

